-- Phase C / C11 — grants so ROLE_RM and ROLE_ANALYST can invoke the PIEDMONT_MCP
-- procedures (now EXECUTE AS CALLER) and read the DEMO_CREDIT source objects they touch.
--
-- IMPORTANT: both roles get IDENTICAL read access here. The A/B differentiation is enforced
-- INSIDE the procedures (CURRENT_ROLE()='ROLE_ANALYST' -> dollar fields returned as NULL),
-- because the procedures return VARIANT/JSON and Snowflake masking policies cannot apply to
-- constructed JSON. See planning/architecture.md ADR-003 / plan.md step 11.
--
-- Run as a role with MANAGE GRANTS (SECURITYADMIN).

USE ROLE SECURITYADMIN;

-- ---- Source schema USAGE (DATABASE DEMO_CREDIT usage already granted in Phase B) ----
GRANT USAGE ON SCHEMA DEMO_CREDIT.CIF TO ROLE ROLE_RM;
GRANT USAGE ON SCHEMA DEMO_CREDIT.AFS TO ROLE ROLE_RM;
GRANT USAGE ON SCHEMA DEMO_CREDIT.CDL TO ROLE ROLE_RM;
GRANT USAGE ON SCHEMA DEMO_CREDIT.DEP TO ROLE ROLE_RM;
GRANT USAGE ON SCHEMA DEMO_CREDIT.CIF TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA DEMO_CREDIT.AFS TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA DEMO_CREDIT.CDL TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA DEMO_CREDIT.DEP TO ROLE ROLE_ANALYST;

-- ---- SELECT on the specific source objects the 6 procedures read ----
GRANT SELECT ON TABLE DEMO_CREDIT.CIF.CIF_CSTMR_MSTR            TO ROLE ROLE_RM;
GRANT SELECT ON TABLE DEMO_CREDIT.AFS.AFS_VDE_OBLIGATION_ROOT   TO ROLE ROLE_RM;
GRANT SELECT ON TABLE DEMO_CREDIT.AFS.AFS_VDE_REPAYMENT_SCHEDULE TO ROLE ROLE_RM;
GRANT SELECT ON VIEW  DEMO_CREDIT.AFS.AFS_V_REVOLVER_USAGE      TO ROLE ROLE_RM;
GRANT SELECT ON TABLE DEMO_CREDIT.CDL.CDL_FACTENTITYRATING      TO ROLE ROLE_RM;
GRANT SELECT ON TABLE DEMO_CREDIT.DEP.DEP_BAL_RECORD            TO ROLE ROLE_RM;

GRANT SELECT ON TABLE DEMO_CREDIT.CIF.CIF_CSTMR_MSTR            TO ROLE ROLE_ANALYST;
GRANT SELECT ON TABLE DEMO_CREDIT.AFS.AFS_VDE_OBLIGATION_ROOT   TO ROLE ROLE_ANALYST;
GRANT SELECT ON TABLE DEMO_CREDIT.AFS.AFS_VDE_REPAYMENT_SCHEDULE TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW  DEMO_CREDIT.AFS.AFS_V_REVOLVER_USAGE      TO ROLE ROLE_ANALYST;
GRANT SELECT ON TABLE DEMO_CREDIT.CDL.CDL_FACTENTITYRATING      TO ROLE ROLE_ANALYST;
GRANT SELECT ON TABLE DEMO_CREDIT.DEP.DEP_BAL_RECORD            TO ROLE ROLE_ANALYST;

-- ---- CREDIT_MEMO_DB: db/schema usage + EXECUTE(USAGE) on the 6 procedures ----
GRANT USAGE ON DATABASE CREDIT_MEMO_DB            TO ROLE ROLE_RM;
GRANT USAGE ON SCHEMA CREDIT_MEMO_DB.CREDIT_RISK  TO ROLE ROLE_RM;
GRANT USAGE ON DATABASE CREDIT_MEMO_DB            TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA CREDIT_MEMO_DB.CREDIT_RISK  TO ROLE ROLE_ANALYST;

GRANT USAGE ON PROCEDURE CREDIT_MEMO_DB.CREDIT_RISK.FIND_OBLIGOR(VARCHAR)                     TO ROLE ROLE_RM;
GRANT USAGE ON PROCEDURE CREDIT_MEMO_DB.CREDIT_RISK.LIST_FACILITIES(NUMBER)                   TO ROLE ROLE_RM;
GRANT USAGE ON PROCEDURE CREDIT_MEMO_DB.CREDIT_RISK.GET_RISK_RATING_TREND(NUMBER,NUMBER)      TO ROLE ROLE_RM;
GRANT USAGE ON PROCEDURE CREDIT_MEMO_DB.CREDIT_RISK.GET_REVOLVER_USAGE_TREND(NUMBER,NUMBER)   TO ROLE ROLE_RM;
GRANT USAGE ON PROCEDURE CREDIT_MEMO_DB.CREDIT_RISK.GET_BALANCE_TREND(NUMBER,NUMBER)          TO ROLE ROLE_RM;
GRANT USAGE ON PROCEDURE CREDIT_MEMO_DB.CREDIT_RISK.GET_PAYMENT_HISTORY(NUMBER,NUMBER)        TO ROLE ROLE_RM;

GRANT USAGE ON PROCEDURE CREDIT_MEMO_DB.CREDIT_RISK.FIND_OBLIGOR(VARCHAR)                     TO ROLE ROLE_ANALYST;
GRANT USAGE ON PROCEDURE CREDIT_MEMO_DB.CREDIT_RISK.LIST_FACILITIES(NUMBER)                   TO ROLE ROLE_ANALYST;
GRANT USAGE ON PROCEDURE CREDIT_MEMO_DB.CREDIT_RISK.GET_RISK_RATING_TREND(NUMBER,NUMBER)      TO ROLE ROLE_ANALYST;
GRANT USAGE ON PROCEDURE CREDIT_MEMO_DB.CREDIT_RISK.GET_REVOLVER_USAGE_TREND(NUMBER,NUMBER)   TO ROLE ROLE_ANALYST;
GRANT USAGE ON PROCEDURE CREDIT_MEMO_DB.CREDIT_RISK.GET_BALANCE_TREND(NUMBER,NUMBER)          TO ROLE ROLE_ANALYST;
GRANT USAGE ON PROCEDURE CREDIT_MEMO_DB.CREDIT_RISK.GET_PAYMENT_HISTORY(NUMBER,NUMBER)        TO ROLE ROLE_ANALYST;

-- ---- MCP server USAGE (so the role can invoke tools through PIEDMONT_MCP) ----
GRANT USAGE ON MCP SERVER CREDIT_MEMO_DB.CREDIT_RISK.PIEDMONT_MCP TO ROLE ROLE_RM;
GRANT USAGE ON MCP SERVER CREDIT_MEMO_DB.CREDIT_RISK.PIEDMONT_MCP TO ROLE ROLE_ANALYST;
